<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>New Request</name>
   <tag></tag>
   <elementGuidId>ea16b42c-5c59-458c-86a1-4108a98eb3c2</elementGuidId>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <authorizationRequest>
      <authorizationInfo>
         <entry>
            <key>bearerToken</key>
            <value>eyJraWQiOiIrR3JkYzNUZDJ2bU1GM1dtbzZtYnQ1bWRwNmNEeXBjYkZlU2J2bDVMeVwvRT0iLCJhbGciOiJSUzI1NiJ9.eyJsYXN0TmFtZSI6IlRlc3QgVXNlciIsImNvdW50cnkiOiJTRSIsInN1YiI6IjRhZDY2ZDFiLTA4ODItNGNiYy1hN2ZkLTMwOGI1NzIxZGI1YyIsImdyb3VwSWQiOiI3YTdmZTYyMS1kMTFhLTRkMzEtODVlMC04M2FmOTNlZGRiNmYiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtbm9ydGgtMS5hbWF6b25hd3MuY29tXC9ldS1ub3J0aC0xX0dhTHF3dXdPSyIsImxhbmd1YWdlIjoiZW4iLCJ0eXBlIjoiaW50ZXJuYWwiLCJwZXJtaXNzaW9ucyI6ImlhbTpzdXBlcl9hZG1pbiBldGE6cmVhZCBldGE6d3JpdGUgZXRhOmZsYWcgdW5pdHM6cmVhZCB1bml0czp3cml0ZSBhaXJjOnJlYWQgYWlyYzp3cml0ZSBldGE6dmlwIiwiY3VzdG9tOnBob25lTnVtYmVyIjoiKzc3Nzc3NzciLCJhdXRoX3RpbWUiOjE3MDkxOTE3MTIsImV4cCI6MTcwOTIzNDkxMSwiaWF0IjoxNzA5MTkxNzEyLCJqdGkiOiI3NGJhMzJjNC04YWViLTQ5NDQtYmIzNy01ZjcyYjBjNzk3NTQiLCJlbWFpbCI6InRlc3QuY2FuYXJ5c0B0aXFxZS5jb20iLCJtZmFBcHBBY3RpdmF0ZWQiOiJmYWxzZSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJsb2dpblRpbWVzIjoiMTcwOTE5MTcxMiAxNzA5MTg4MjIzIiwiY29nbml0bzp1c2VybmFtZSI6InRlc3QuY2FuYXJ5c1thdF10aXFxZS5jb20iLCJnaXZlbl9uYW1lIjoiQ2FuYXJ5IiwidXNlcklkIjoiNGFkNjZkMWItMDg4Mi00Y2JjLWE3ZmQtMzA4YjU3MjFkYjVjIiwib3JpZ2luX2p0aSI6IjcxMmM1ZTlhLWVmZDMtNGRmMC1hNjdjLTNhZWM3ZWRiZGQwYyIsImZpcnN0TmFtZSI6IkNhbmFyeSIsImF1ZCI6IjVzYWthaWx2OHQzaW1iYzY0djkxMTNoazNhIiwiYnVzaW5lc3NBcmVhIjoiIiwiZXZlbnRfaWQiOiJhZTdjMWFmOC00MzY5LTQxZDItOWMxMy1kYTliMGZiMDVjNDYiLCJwaG9uZSI6Iis3Nzc3Nzc3IiwidG9rZW5fdXNlIjoiaWQiLCJmYW1pbHlfbmFtZSI6IlRlc3QgVXNlciJ9.QV4gOS_YuyBSForHiDKxyTA2fekxqxiLg8L9EFm6wBiXOQwD40YWl65DsmhFJtbM4lv47gtmnycrbNb8YpDaTGGRnJXuAgqzrwXMSlIShandC5OOwcI8QPTHyK9gu8G0cYzAizRsq9SEbCHm9lc6gz8qhbFKiZ6kTpk9NHwGDo9BPDdGa3Ss6_jDXGpR-SaMFxLge82XMloIp9h1ZvUjCmS0-vrXXFkYx0k6Mww9OpWT4rnKFfHPLbKXaiqZW4FbJsta2nQ3hSvf08l2COXlmqzviOaw_utxHsD4LZ-OIdlTFt3KZNFcXMVR666WCwxv_V6fZTUYALVp6tM2XiAEIw</value>
         </entry>
      </authorizationInfo>
      <authorizationType>Bearer</authorizationType>
   </authorizationRequest>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>0</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Bearer eyJraWQiOiIrR3JkYzNUZDJ2bU1GM1dtbzZtYnQ1bWRwNmNEeXBjYkZlU2J2bDVMeVwvRT0iLCJhbGciOiJSUzI1NiJ9.eyJsYXN0TmFtZSI6IlRlc3QgVXNlciIsImNvdW50cnkiOiJTRSIsInN1YiI6IjRhZDY2ZDFiLTA4ODItNGNiYy1hN2ZkLTMwOGI1NzIxZGI1YyIsImdyb3VwSWQiOiI3YTdmZTYyMS1kMTFhLTRkMzEtODVlMC04M2FmOTNlZGRiNmYiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtbm9ydGgtMS5hbWF6b25hd3MuY29tXC9ldS1ub3J0aC0xX0dhTHF3dXdPSyIsImxhbmd1YWdlIjoiZW4iLCJ0eXBlIjoiaW50ZXJuYWwiLCJwZXJtaXNzaW9ucyI6ImlhbTpzdXBlcl9hZG1pbiBldGE6cmVhZCBldGE6d3JpdGUgZXRhOmZsYWcgdW5pdHM6cmVhZCB1bml0czp3cml0ZSBhaXJjOnJlYWQgYWlyYzp3cml0ZSBldGE6dmlwIiwiY3VzdG9tOnBob25lTnVtYmVyIjoiKzc3Nzc3NzciLCJhdXRoX3RpbWUiOjE3MDkxOTE3MTIsImV4cCI6MTcwOTIzNDkxMSwiaWF0IjoxNzA5MTkxNzEyLCJqdGkiOiI3NGJhMzJjNC04YWViLTQ5NDQtYmIzNy01ZjcyYjBjNzk3NTQiLCJlbWFpbCI6InRlc3QuY2FuYXJ5c0B0aXFxZS5jb20iLCJtZmFBcHBBY3RpdmF0ZWQiOiJmYWxzZSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJsb2dpblRpbWVzIjoiMTcwOTE5MTcxMiAxNzA5MTg4MjIzIiwiY29nbml0bzp1c2VybmFtZSI6InRlc3QuY2FuYXJ5c1thdF10aXFxZS5jb20iLCJnaXZlbl9uYW1lIjoiQ2FuYXJ5IiwidXNlcklkIjoiNGFkNjZkMWItMDg4Mi00Y2JjLWE3ZmQtMzA4YjU3MjFkYjVjIiwib3JpZ2luX2p0aSI6IjcxMmM1ZTlhLWVmZDMtNGRmMC1hNjdjLTNhZWM3ZWRiZGQwYyIsImZpcnN0TmFtZSI6IkNhbmFyeSIsImF1ZCI6IjVzYWthaWx2OHQzaW1iYzY0djkxMTNoazNhIiwiYnVzaW5lc3NBcmVhIjoiIiwiZXZlbnRfaWQiOiJhZTdjMWFmOC00MzY5LTQxZDItOWMxMy1kYTliMGZiMDVjNDYiLCJwaG9uZSI6Iis3Nzc3Nzc3IiwidG9rZW5fdXNlIjoiaWQiLCJmYW1pbHlfbmFtZSI6IlRlc3QgVXNlciJ9.QV4gOS_YuyBSForHiDKxyTA2fekxqxiLg8L9EFm6wBiXOQwD40YWl65DsmhFJtbM4lv47gtmnycrbNb8YpDaTGGRnJXuAgqzrwXMSlIShandC5OOwcI8QPTHyK9gu8G0cYzAizRsq9SEbCHm9lc6gz8qhbFKiZ6kTpk9NHwGDo9BPDdGa3Ss6_jDXGpR-SaMFxLge82XMloIp9h1ZvUjCmS0-vrXXFkYx0k6Mww9OpWT4rnKFfHPLbKXaiqZW4FbJsta2nQ3hSvf08l2COXlmqzviOaw_utxHsD4LZ-OIdlTFt3KZNFcXMVR666WCwxv_V6fZTUYALVp6tM2XiAEIw</value>
      <webElementGuid>005a8cb9-9dfe-4faf-b9a8-ddd27294aca6</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.3.1</katalonVersion>
   <maxResponseSize>0</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>https://dummy.restapiexample.com/api/v1/employees</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>0</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
